GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json


{
    "text": "Hello the bread"
}

###


POST http://localhost:3001/todo/new
Content-Type: application/json


{
    "text": "Hello the get some milk"
}


###

DELETE http://localhost:3001/todo/delete/63ee4317045a39ab7c3cd533


###

PUT http://localhost:3001/todo/complete/63ee4313045a39ab7c3cd52f